[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "nodejs_20"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "cd backend && python3 -m pip install -r requirements.txt",
  "cd frontend && npm install && npm run build"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
